### ISSUE TITLE
Update wiki for cronjob & scheduling

### ISSUE THREAD

**Issue by mostafa8026** [diffal/diffal#10]
در آینده نیاز داریم که با cronjob کار کنیم. باید ابتدا در مورد cronjob تحقیق کنید و یک صفحه ویکی برای استفاده از این مفهوم در nest.js ایجاد کنید. توضیحات بیشتر در لینک زیر هست:
https://docs.nestjs.com/techniques/task-scheduling
در ضمن باید یک نمونه گیت ایجاد شود و در همین تسک کامنت شود.

**Comment by fahimi85** [comment]
https://github.com/diffal/diffal/wiki/cronjob#cronjobs @mostafa8026
