### ISSUE TITLE
Add swagger to the application

### ISSUE THREAD

**Issue by mostafa8026** [diffal/diffal#25]
با توجه به توضیحاتی که توی کلاس دادیم، swagger‌ به پروژه اضافه بشه

**Comment by mostafa8026** [comment]
اینو اضافه کردی؟ خیلی بهش نیاز هست. زودتر اضافه کن پول ریکوئست بده.

**Comment by fahimi85** [comment]
import { NestFactory } from '@nestjs/core';
import { NestExpressApplication } from '@nestjs/platform-express';
import { join } from 'path';
import { AppModule } from './app.module';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule);
  const options = new DocumentBuilder()
    .setTitle('Our Api Specification')
    .setVersion('1.0.0')
    .setDescription('Our Api Description')
    .addBearerAuth()
    .build();

  const document = SwaggerModule.createDocument(app, options);

  SwaggerModule.setup('/docs', app, document);
  app.useStaticAssets(join(__dirname, 'public'));
  const PORT = process.env.PORT || 3000;
  await app.listen(PORT, () => console.log(`Listening on ${PORT}`));
}
bootstrap();

**Comment by fahimi85** [comment]
@nestjs/swagger  swagger-ui-express

**Comment by fahimi85** [comment]
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true,
    "plugins": ["@nestjs/swagger/plugin"]
  }
}
