### ISSUE TITLE
Create post module & entity

### ISSUE THREAD

**Issue by mostafa8026** [diffal/diffal#4]
هر پست فعلا شامل اطلاعات زیر است:
* عنوان،
* متن پست (این ستون بصورت nvarchar - max در نظر گرفته شود)

فعلا نیازی به ایجاد relationها نیست. در ادامه زمانی که اطلاعات دیگر جداول هم کامل شود روابط را ایجاد خواهیم کرد.
فراموش نشود که باید همه روتهای مربوط به CRUD همراه با dtoهای مورد نظر ایجاد شوند.

**Comment by fahimi85** [comment]
Please put the tasks inside the todo to start the project Mr @mostafa8026

**Comment by mostafa8026** [comment]
Ok, I'll do it today.

**Comment by mostafa8026** [comment]
@fahimi85 
توضیحات بروز شد.

**Comment by alieidelkhani** [comment]
hi mr @mostafa8026 
sorry for the diturbation
can i asign mr farman as one of my viewers?
