### ISSUE TITLE
Create an exception filter that log all http exceptions

### ISSUE THREAD

**Issue by mostafa8026** [diffal/diffal#5]
می‌بایست یک exception filter ایجاد شود که همه خطاها از نوع http exception را دریافت کرده و در یک جدول برای audit ذخیره کند. اسم جدول و محتوای ستون‌ها به دلخواه انتخاب گردد.

**Comment by fahimi85** [comment]
Please assign me the Create an exception filter that log all http exceptions #5 as well @mostafa8026

**Comment by mostafa8026** [comment]
@fahimi85 
Done

**Comment by fahimi85** [comment]
i have a problem in push: @mostafa8026 
git push
remote: Permission to diffal/diffal.git denied to fahimi85.
fatal: unable to access 'https://github.com/diffal/diffal.git/': The requested URL returned error: 403

**Comment by mostafa8026** [comment]
You have to use ssh, It is better. by the way if you want to use http, you have to provide your username and password. If there is any problem, we'll check it at the class.

**Comment by fahimi85** [comment]
I used ssh-key to clone it and i don't have any problem . But in push process i have :
$ git push
Enter passphrase for key '/c/Users/acer/.ssh/id_rsa': 
ERROR: Permission to diffal/diffal.git denied to fahimi85.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.  @mostafa8026

**Comment by mostafa8026** [comment]
I sent an invitation, could you please accept it, then check (git push) again, let me know if problem occur again
