### ISSUE TITLE
Create an interceptor to log every request in database

### ISSUE THREAD

**Issue by mostafa8026** [diffal/diffal#6]
همانطور که از نام تسک مشخص هست، نیاز هست تا با استفاده از interceptor همه درخواستها در دریتابیس برای audit لاگ گرفته شود. محتوای دیتابیس به دلخواه شماست

**Comment by fahimi85** [comment]
for find all request , can i use? :     const body = context.switchToHttp().getRequest().body;
@mostafa8026

**Comment by mostafa8026** [comment]
Yes you can.

**Comment by fahimi85** [comment]
Please assign me this issue @mostafa8026

**Comment by mostafa8026** [comment]
done

**Comment by fahimi85** [comment]
Thanks, please Create issue of swagger @mostafa8026

**Comment by mostafa8026** [comment]
#25 added

**Comment by fahimi85** [comment]
I'm sorry, it looks like I've done push on brunchmaster. Is this access available to us?
Fortunately, at least the brunch was up to date. @mostafa8026

**Comment by mostafa8026** [comment]
خب اگه باز هم هست دقت کنید که پوش نکنید. تو جلسه اول هم گفتم. حالا بررسی میکنم که اشکالی پیش امده باشه یا نه

**Comment by fahimi85** [comment]
can we use this code?  git reset --hard a03fb44 @mostafa8026

**Comment by mostafa8026** [comment]
اونکه من تصحیح میکنم مشکلی نداره. ولی دقت کن که دوباره پیش نیاد

**Comment by mostafa8026** [comment]
برنچ رو هم permission پوش رو برداشتم که دوباره این مشکل پیش نیاد

**Comment by Rzix** [comment]
![image](https://user-images.githubusercontent.com/85103119/157179731-6cdea28b-4a22-4297-8b89-59609789bd41.png)

این خطا فکر میکنم از بخش log برام اتفاق افتاده خواستم ببینم کسه دیگه اییم موقع ران کردن به این مشکل خورده؟

**Comment by Rzix** [comment]
@fahimi85  @we4netbot  @miladworkac  @fahimi85
